dependency loop solved: event server requires ckpt client, ckpt client uses event client.  simple safplus start shell script for no-python systems. Other small fixes discovered using ARM

diff --git a/src/SAFplus/build/base-images/scripts/safplus b/src/SAFplus/build/base-images/scripts/safplus
--- a/src/SAFplus/build/base-images/scripts/safplus
+++ b/src/SAFplus/build/base-images/scripts/safplus
@@ -1,134 +1,59 @@
 #!/bin/bash
-###############################################################################
-#
-# Copyright (C) 2002-2009 by OpenClovis Inc. All  Rights Reserved.
+# Simple SAFplus start script. This can be used as a replacement to the python
+# "safplus start".  However, it lacks the full functionality of "safplus start".
+
+# *** It is meant to be as simple as possible ***
+
+# This script expects that TIPC is either already loaded and configured or
+# that tipc.ko exists in $ASP_DIR/modules and tipc-config exists in your path.
 # 
-# The source code for  this program is not published  or otherwise 
-# divested of  its trade secrets, irrespective  of  what  has been 
-# deposited with the U.S. Copyright office.
-# 
-# This program is  free software; you can redistribute it and / or
-# modify  it under  the  terms  of  the GNU General Public License
-# version 2 as published by the Free Software Foundation.
-# 
-# This program is distributed in the  hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied  warranty  of 
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
-# General Public License for more details.
-# 
-# You  should  have  received  a  copy of  the  GNU General Public
-# License along  with  this program. If  not,  write  to  the 
-# Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
-#
-###############################################################################
 
-# killproc : comment so that /etc/rc will stop ASP if 
-#            appropriately symlinked
+export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+#export ASP_DIR=$(realpath $(pwd)/..)
+export ASP_DIR=$(readlink -f $DIR/..)
+source $ASP_DIR/etc/asp.conf
 
-start() {
-    $ASP_SCRIPT start $*
-    return $?
-}
+export ASP_BINDIR=$ASP_DIR/bin
+export ASP_CPM_CWD=$ASP_DIR/var/run
+export ASP_CONFIG=$ASP_DIR/etc
+export ASP_MULTINODE=0
+export ASP_SIMULATION=0
+export BUILD_TIPC=1
 
-stop() {
-    $ASP_SCRIPT stop
-    return $?
-}
+export ASP_APP_BINDIR=$ASP_DIR/bin
+export ASP_RUNDIR=$ASP_DIR/var/run
+export ASP_DBDIR=$ASP_DIR/var/lib
+export ASP_LOGDIR=$ASP_DIR/var/log
+export ASP_NODENAME=$NODENAME
+export ASP_NODEADDR=$DEFAULT_NODEADDR
 
-restart() {
-    $ASP_SCRIPT restart $*
-    return $?
-}
+mkdir -p $ASP_RUNDIR
+mkdir -p $ASP_DBDIR
+mkdir -p $ASP_LOGDIR
 
-status() {
-    $ASP_SCRIPT status
-    return $?
-}
+export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ASP_DIR}/lib:${ASP_DIR}/lib/openhpi:/usr/lib:/usr/local/lib
+export PYTHONPATH=$PYTHONPATH:${ASP_DIR}/lib
 
-consolestart() {
-    $ASP_SCRIPT console
-    return $?
-}
-
-zap() {
-    $ASP_SCRIPT zap
-    return $?
-}
-
-help() {
-    $ASP_SCRIPT help
-    return $?
-}
-
-# We need to get the working dir for the original
-# init.d/asp script, not any of the symlinks (or
-# symlinks to symlinks) to it.  Thus, we must find
-# the original target.
-
-SOURCE=$0
-DIR="$( dirname "$SOURCE" )"
-while [ -h "$SOURCE" ]
-do 
-  SOURCE="$(readlink "$SOURCE")"
-  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
-  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
-done
-ASP_SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-ASP_DIR=`cd $ASP_SCRIPT_DIR/../../; pwd` || exit 1
-source ${ASP_DIR}/etc/asp.conf
-
-#Get the OS first
-THIS_OS=`uname`
-if [ "SunOS" = $THIS_OS ] 
-then
-    ASP_SCRIPT=$ASP_DIR/etc/asp_solaris.py
+# User can set his own log severity: export CL_LOG_SEVERITY=ERROR
+#type $ASP_DIR/modules/tipc.ko >/dev/null 2>&1
+if [ -a ${ASP_DIR}/modules/tipc.ko ]; then
+  insmod $ASP_DIR/modules/tipc.ko
 else
-    ASP_SCRIPT=$ASP_DIR/etc/safplus_watchdog_start.py
+  echo "TIPC kernel module not found in $ASP_DIR/modules.  Expecting that it is already loaded."
 fi
 
+type tipc-config >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "tipc-config not found in your path.  Expecting the TIPC is already properly configured."
+else
+  tipc-config -netid=$TIPC_NETID -addr=1.1.$DEFAULT_NODEADDR -be=eth:eth0
+fi
 
-#echo "ASP script directory is $ASP_SCRIPT_DIR"
+#shift will consume more args
+echo SAFPLUS dir: $ASP_DIR
+echo $ASP_BINDIR/safplus_amf -c 0 -n $NODENAME -l $DEFAULT_NODEADDR $@
+#exec gdb $ASP_BINDIR/safplus_amf
+cd $ASP_RUNDIR
+exec $ASP_BINDIR/safplus_amf -c 0 -n $NODENAME -l $DEFAULT_NODEADDR $@
 
-case "$1" in
-    start)
-        shift
-	start $*
-        RETVAL=$?
-	;;
-    
-    stop)
-	stop
-        RETVAL=$?
-	;;
-    
-    status)
-	status
-        RETVAL=$?
-        ;;
 
-    restart)
-	restart
-        shift
-        RETVAL=$?
-        ;;
-
-    consolestart)
-	consolestart
-        RETVAL=$?
-	;;
-
-    zap)
-        zap
-        RETVAL=$?
-        ;;
-    
-    help)
-        help
-        RETVAL=$?
-        ;;
-    *)
-        help
-        RETVAL=1
-esac
-
-exit $RETVAL
